# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /client

# Copy the package.json and package-lock.json files to the container
COPY package.json /client/package.json
COPY package-lock.json /client/package-lock.json

# Install the dependencies
RUN npm i

# Copy the rest of the application code to the container
COPY . .

# Set environment variables
ENV REACT_APP_BASE_URL=http://localhost:8080/api/
ENV REACT_APP_CLOUD_NAME=dpbhp5ury
ENV REACT_APP_CLOUD_PRESET=ml_default
ENV REACT_APP_CLOUD_API_KEY=16892114678836
ENV REACT_APP_CLOUD_API_SECRET=xyGefjjzHufGEcQDwyyjNUrR1tk
ENV REACT_APP_SOCKET_SERVER=http://localhost:8080

# Serve the app using a static web server
CMD ["npm", "start"]
