version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - "80:80"
  db:
    image: postgres
    restart: always
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
  api:
    build:
      context: ./api
      args: 
        - NODE_ENV=development
    container_name: api
    env_file:
            - ./api/.env
    ports:
      - 8080:8080
    command: >
      sh -c "npm run migration:up && npm run migration:seed || true && npm run dev"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
  client:
    build:
      context: ./client
    container_name: client
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    depends_on:
      - api

volumes:
  postgres_data:
