version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
  db:
    image: postgres
    restart: always
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - db
  # client:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api

volumes:
  postgres_data:
